### ISSUE TITLE
Thumbnail microservice

### ISSUE THREAD

**Issue by enmust** [geocollections/geocase-ui#102]
view [geocase-thumbnail](https://github.com/geocollections/geocase-thumbnail) repo

https://github.com/geocollections/geocase-thumbnail/issues/1

**Comment by enmust** [comment]
Now possible to test current version from https://geocase.geocollections.info/thumbnail/

**Comment by git-arbitrarysystems** [comment]
> Now possible to test current version from https://geocase.geocollections.info/thumbnail/

I rewrote the service and i will deploy it on an mfn-server soon. You can of course test it out locally as well.

**Comment by enmust** [comment]
service is now in use
