### ISSUE TITLE
import georeferenced data from geocase to mfn-geoserver

### ISSUE THREAD

**Issue by alexanderbuhl** [geocollections/geocase-ui#109]
Hi Enar,

I'm working first time with solr and I have some questions to this.
I think there are two ways to import the georeferenced data to our mfn-geoserver:

[1. solr-data-store](https://docs.geoserver.org/latest/en/user/community/solr/configure.html#mapping-documents-to-layers)
if I try to connect the geocase-solr-server with mfn-geoserver I got no response. What i need is the provided link to the SOLR server that provides the documents or collections. I try https://geocase.geocollections.info/api, https://geocase.geocollections.info/solr/ but nothing is happens!?

[2. solr-geojson-response](https://lucene.apache.org/solr/guide/6_6/response-writers.html#ResponseWriters-GeoJSONResponseWriter)
Another easy way could be a solr-geojson-response because the geojson is a standardized format and geoserver can handle with that. But if i try that i get the error Missing parameter: 'geojson.field':

- https://geocase.geocollections.info/api/?start=0&rows=50&q=*&fq=has_map:true&wt=geojson

How did you name the spatial Solr field in your schema?

- [The possibility of a geojson response would also be an advantage for the geocase-ui because also leaflet can process geojson directly](https://leafletjs.com/reference-1.7.1.html#geojson)

I also tried to make simple [solr spatial search](https://lucene.apache.org/solr/guide/6_6/spatial-search.html):

https://geocase.geocollections.info/api/?start=0&rows=100&q=*&fq=has_map:true,\{!geofilt%20sfield=store\}&pt=52.53794364304724,13.42803955078125&d=10

What am I doing wrong?

- Solr spatial searches could be an advantage for geocase-ui because you can do some spacial geo-searches in the backend and  not filter them in the frontend.  

Best regards, Alex

**Comment by enmust** [comment]
At the time you opened this issue there were some problems and server was down. It is working now.

This url https://geocase.geocollections.info/solr/ redirects to default solr and currently has no use. 

**wt=geojson** also wants parameter **geojson.field={our spatial field here}**. Unfortunately we currently do not have spatial field but I think this can be easily added by combining current latitude and longitude fields for example [LatLonPointSpatialField](https://lucene.apache.org/solr/guide/6_6/spatial-search.html#SpatialSearch-LatLonPointSpatialField)

**Comment by alexanderbuhl** [comment]
I still can't connect to the solr-server. But maybe thats my fault or the geoserver-plugin faild.
But doesn't matter, i think the geojson-response is the better way...
It would be nice if you add LatLonPointSpatialField.
If I am right, this field type will unlock the most spatial search functions of point data?

thanks, Alex

**Comment by enmust** [comment]
> If I am right, this field type will unlock the most spatial search functions of point data?
Yes, according to the docs it should

**Comment by enmust** [comment]
Sorry for the delay but now it is possible to search using spatial field.

I provided some example urls, first one returns geojson field and second one is search example

https://geocase-api.geocollections.info/v2/solr?wt=geojson&geojson.field=coordinates&q=*&fq=has_map:true&fl=latitude,longitude,coordinates

https://geocase-api.geocollections.info/v2/solr?start=0&rows=100&q=*&fq=has_map:true&fq={!geofilt%20sfield=coordinates}&pt=52.5,13.4&d=10&fl=coordinates,latitude,longitude

**Comment by alexanderbuhl** [comment]
Thanks Enar!
# The most effective solr-request to get **all** georeferenced data in geojson!?
Now I do this?
* curl -X GET "https://geocase-api.geocollections.info/v2/solr?start=0&rows=800000&q=*&fq=has_map:true&wt=geojson&geojson.field=coordinates&fl=id,coordinates" -H  "accept: */*" >> geocase_solr.geojson

Is that the right way?

**Comment by enmust** [comment]
Seems ok, probably in the future 'rows' value should be incremented.

**Comment by alexanderbuhl** [comment]
Okay, I can show you a little bit in the web conf. 

see you soon

**Comment by enmust** [comment]
@alexanderbuhl Hey we updated our code so it's returning only distinct coordinates. You should use this url: https://geocase-api.geocollections.info/v2/solr/map?q=*&wt=geojson&geojson.field=coordinates&fl=coordinates&start=0&rows=1000000

(currently 12166 records/points)

**Comment by alexanderbuhl** [comment]
Crazy, 763962 georeferenced objects have only 12166 different coordinates!
You create a new table with primary key coordinates and as attributes the corresponding object Ids, right?
This is nice to rendering only the different coordinates in the map and a object get his associated coordinate with his id.
 
But for the **heatmap** we need all objects with georeference becourse heatmap visualised  the density of all georeferenced objects.
But the request of all objects with georeference is still possible:
https://geocase-api.geocollections.info/v2/solr?start=0&rows=1000000&q=*&fq=has_map:true&wt=geojson&geojson.field=coordinates&fl=id,coordinates

Alex

**Comment by alexanderbuhl** [comment]
@enmust  If I do this:
https://geocase-api.geocollections.info/v2/solr/map?q=*&wt=geojson&geojson.field=coordinates&fl=**id**,coordinates&start=0&rows=10
For the id-field I get a hashtag or something. How can i get all associated ids?

**Comment by enmust** [comment]
Sorry about the delay but for the specimen ids you have to use the other request
