### ISSUE TITLE
Elaborate and implement more detailed imprint, cookie policy and general privacy notice

### ISSUE THREAD

**Issue by falkogloeckler** [geocollections/geocase-ui#110]
For the official launch we need an imprint and general privacy policy. 

1) We need to elaborate a little bit more on the cooky policy (at least list the cookies used and their purpose.

1) The imprint depends on the decision who will run the portal. 

1) The General Privacy Notice should be more or less the same for all European countries. Thus, regarding this there won't be any difference in the text if the portal will be run by MfN or TalTech.

1) We might need also a Disclaimer, that explicitly mentions, that the harvested data is publically available and the institution which runs the portal is not reasonsible for any wrong information or accountable for damages due to erroneous data.
Personal data is published by the data providers. Thus, the maintainer of the portal is not accountable for any infringement of personal rights or any other regulations caused by the data providers.

**Comment by falkogloeckler** [comment]
The [Access page](https://geocase.geocollections.info/access) already tries to cover some aspects of a disclaimer, but needs a revision or should be replaced by the disclaimer. If the latter applies, it might not be so prominentely shown in the main menu, but in the footer. Any preferences?

**Comment by enmust** [comment]
Closing this for now because terms of use are updated along with disclaimer and copyright. If there is a need for some changes then new issue etc can be made
