### ISSUE TITLE
Images for social media (social meta tags)

### ISSUE THREAD

**Issue by ollehints** [geocollections/geocase-ui#151]
Can we make the front page and specimen pages show photo (and/or geocase logo) if shared via FB and other social media platforms?

**Comment by ollehints** [comment]
title / description not translated? 
![image](https://user-images.githubusercontent.com/14974887/106937071-ff52cf00-6725-11eb-8a13-18a409b68acf.png)

**Comment by enmust** [comment]
This should be OK
![image](https://user-images.githubusercontent.com/14908993/110623480-912a7d80-81a5-11eb-8450-35bde71e2d76.png)
![image](https://user-images.githubusercontent.com/14908993/110623548-aacbc500-81a5-11eb-9757-79e2410344a2.png)
