### ISSUE TITLE
GeoCASe and Safari

### ISSUE THREAD

**Issue by rwalcott20** [geocollections/geocase-ui#194]
GeoCASe does not load using a Safari Browser  Version 14.1.2 (16611.3.10.1.6).

All I see is a blank page

**Comment by enmust** [comment]
@rwalcott20 It should work fine. Did you try refreshing the browser it could be a cache issue. Also you could try visiting the page in incognito/private browsing mode.

**Comment by falkogloeckler** [comment]
I can confirm also hat GeoCASe is working as expected in Safari (version 13.1.3) on my machine.
