### ISSUE TITLE
Links on https://geocase.eu/efg are not working

### ISSUE THREAD

**Issue by samleeflang** [geocollections/geocase-ui#222]
ABCDEFG Schema Documentation on the page https://geocase.eu/efg gives an issue.
![image](https://user-images.githubusercontent.com/57710483/193270906-a095471a-a911-4b19-90a9-b36ac8245b41.png)

Additionally most of the links on this page are dead, for example:
- http://terms.tdwg.org/wiki/ABCD_2
- http://terms.tdwg.org/wiki/ABCD_EFG
- https://efg.geocase.eu/documentation/html/efg.html

It makes it difficult to get the XML/XSD of the ABCDEFG extension.

**Comment by enmust** [comment]
https://efg.geocase.eu/documentation/html/efg.html still broken, seems to be invalid cert

**Comment by falkogloeckler** [comment]
Certificate is renewed since a while already.
Closing the issue now
