### ISSUE TITLE
Link mineral/rock names to Mindat 

### ISSUE THREAD

**Issue by ollehints** [geocollections/geocase-ui#24]
Update search index to include mindat_id and mindat_url fields, that come from the mindat_names table, which is linked to identification via simple name matching. 
If a record in portal list view has mindat_id>0 then fullscientificname should become link to mindat.org page using the value from mindat_url field. Mindat.org page should open in new window.
In detail view, we could provide link to Mindat on separate row, showing user also the link address.

**Comment by enmust** [comment]
Do you mean that mindat.org should open in a new pop-up browser window?

**Comment by ollehints** [comment]
yes
