### ISSUE TITLE
Detail page layout

### ISSUE THREAD

**Issue by ollehints** [geocollections/geocase-ui#46]
- In many cases, especially with longer names, it would be better to have the title on separate full width panel, like in geocollections specimen view, it might similarly start with collection code and specimen number (Object ID). Above or below title row (-test which looks better) include fish etc icon and value from the 'recordbasis' field. 
- If recordbasis=fossilspecimen then show 'fullscientificname' and 'names' in italic (in future it will be possibly to check names and make italic only for species and genus names).
- If 'names' includes more than one, show them all on separate row, with label 'identifications'.
- Make images smaller (max width/height 400px?), and if multiple images are present (in field 'images'), show all of them.
- Add additional fields from the index:
  - typestatus - this should come as the first field and made prominent as type specimens are especially important
- There should be separate section in the bottom on text table, perhaps with smaller font / different style that provides data on:
  - contact data - need to be added to the index first - but it seems BHIT does not index this data - then it might be extracted from XML
  - datasetowner
  - datasourcecountry
  - last_harvested_processing
  - providername
  - provideraddress
  - providerurl

**Comment by enmust** [comment]
Records with multiple images: 189451
Records with multiple names: ?page=1&paginate_by=10&q=huberti
