### ISSUE TITLE
Advanced search should be case insensitive

### ISSUE THREAD

**Issue by ollehints** [geocollections/geocase-ui#47]
Advanced search should be case insensitive - this needs to implemented probably in solr config before index (re)creation.
Cf
http://geocase.geocollections.info/?fastsearch=%2a&fullscientificname__equals=gold
and
http://geocase.geocollections.info/?fastsearch=%2a&fullscientificname__equals=Gold

**Comment by enmust** [comment]
Some possible solutions: 

- https://stackoverflow.com/questions/8240329/solr-case-insensitive-search (this seems like it would need converting to lowercase in client side)

- https://javadeveloperzone.com/solr/solr-case-insensitive-indexing-searching/

- https://stackoverflow.com/questions/2053214/how-to-create-a-case-insensitive-copy-of-a-string-field-in-solr (some useful info which type should be used etc.)

**Comment by a-kroh** [comment]
Case sensitivity is responsible for many supposed errors reported by users - any news on a solution?

**Comment by enmust** [comment]
Well currently the only search field which doesn't check case sensitivity is 'Find quickly'. 
We haven't yet tested the possible solutions, but currently the fast fix would be to use wildcard symbol which is asterisk '*'

**Comment by ollehints** [comment]
Problem now solved by changing solr index data types and behavior so that case is not considered in searches for name, locality, stratigraphy, etc fields: http://geocase.geocollections.info/search?fullscientificname__contains=asaphUS&locality__contains=kohtla
However, search parameters may need adjusting internally in the app -- wildcard is not needed any more in most cases (the strings are split into tokens in the index, thus fq=providername:stuttgart is equal to fq=providername:*stuttgart*, in some cases added * may have undesired effects).

**Comment by ollehints** [comment]
Search is OK, but facets are now "tokenized", probably need to duplicate facet fields in the index as strings:
https://stackoverflow.com/questions/47547613/solr-facet-with-text-field-how-to-stop-solr-tokenize-it-into-separate-tokens-i

**Comment by ollehints** [comment]
Some fields changed back to string and text_index (the latter with solr.KeywordTokenizerFactory) to preserve keywords for facets. string field highertaxon_facet was added for faceting.
