### ISSUE TITLE
Static pages

### ISSUE THREAD

**Issue by ollehints** [geocollections/geocase-ui#48]
We need static pages as on the Drupal site. The easiest way would be to have html in individual files, one for each page, to be compiled into the app. At some point all current pages are needed, retaining the old urls. In addition, we need an /about page, especially if the front page will be seach and data. We could start implementing the feature with /about page.

**Comment by enmust** [comment]
Other urls: 

- /join

- /tutorial

- /project

- /efg

- /partners_and_providers

- /contact

- /links

- /imprint

+ also front page

**Comment by ollehints** [comment]
As a temporary solution, we can use geocollections API to host static pages content:
- /partners_and_providers **Partners and members** https://api.geocollections.info/page/72
- /about **About GeoCASe** https://api.geocollections.info/page/73
- /access **Data access** https://api.geocollections.info/page/74

**Comment by enmust** [comment]
Did some research and I believe our current solution is actually pretty good for our use case, it just depends who needs to do the editing. 

There are some great [options](https://jamstack.org/generators/) but implementing (if possible at all) them into already existing projects would mean a lot of rewrite. 

We could experiment with markdown  https://v3.vuejs.org/examples/markdown.html

**Comment by enmust** [comment]
We can use html in translation files so it would be possible to use that.
