### ISSUE TITLE
Specimen page: fossils

### ISSUE THREAD

**Issue by ollehints** [geocollections/geocase-ui#72]
From Andreas Kroh (2020-09-24):
![image](https://user-images.githubusercontent.com/14974887/94335937-c708ea80-ffe7-11ea-9b71-9267a56c26bd.png)

**Comment by ollehints** [comment]
Specimens for testing (from M. Rasser):
Below please find 10 typical records from the SMNS collection. I hope that this is what I was supposed to send you?
We had not included the localities in this data export, a strategy that is currently under discussion in our museum. Maybe this will change in the near future.

- http://geocase.geocollections.info/specimen/351119
- http://geocase.geocollections.info/specimen/345169
- http://geocase.geocollections.info/specimen/309429
- http://geocase.geocollections.info/specimen/345624
- http://geocase.geocollections.info/specimen/307132
- http://geocase.geocollections.info/specimen/322391
- http://geocase.geocollections.info/specimen/315182
- http://geocase.geocollections.info/specimen/303636
- http://geocase.geocollections.info/specimen/306087
- http://geocase.geocollections.info/specimen/345136

**Comment by ollehints** [comment]
Specimens for testing (from A. Kroh):
Collection: NHMW-Geo 
ID           Object ID
432565  1861/0033/0002
419054  2009z0180/0025               
419138  2009z0034/0001               
424557  2000B0014/0001
413274  2005z0036/0009
419092  2009z0180/0063
419029  2009B0003/0001
435823  1987/0044/0063
419253  1987/0045/0337
432614  1980/0015/0001

**Comment by enmust** [comment]
need to add reference field from source

**Comment by enmust** [comment]
Closing for now because most fields from the given examples were added
